change internalKVDB to true by default
portworx/helm pull request #412
Opened 2022-07-22 17:14 UTC by haibinxie

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** (optional)
Closes #

**Special notes for your reviewer**:

2022-07-22 17:18 UTC, pure-jliao approved these changes

2022-07-22 19:30 UTC, piyush-nimbalkar requested changes
Won't this break migrated customers who have etcdEndpoints set? We will default to internal kvdb for them and the etcd endpoints would be ignored. 
I guess we will have to update the logic in the storagecluster spec.

2022-07-22 19:30 UTC, piyush-nimbalkar commented on charts/portworx/values.yaml
> +internalKVDB: true                    # internal KVDB
Let's change the default in the storagecluster template as well - https://github.com/portworx/helm/blob/operator-migration/charts/portworx/templates/storage-cluster.yaml#L4.

2022-07-22 19:47 UTC, haibinxie commented on charts/portworx/values.yaml
> +internalKVDB: true                    # internal KVDB
values.yaml is just an example to use, it won't break existing customer. if we change the template then it would break customers who use a values.yaml that does not specify the flag. since it's already released to Mambu let's not change the template.

2022-07-22 19:51 UTC, haibinxie commented
> Won't this break migrated customers who have etcdEndpoints set? We will default to internal kvdb for them and the etcd endpoints would be ignored. I guess we will have to update the logic in the storagecluster spec.

the migrated customer should have no impact as they need to upgrade based on their original values.yaml through "helm get values".

2022-07-22 20:52 UTC, piyush-nimbalkar commented
> > Won't this break migrated customers who have etcdEndpoints set? We will default to internal kvdb for them and the etcd endpoints would be ignored. I guess we will have to update the logic in the storagecluster spec.
> 
> the migrated customer should have no impact as they need to upgrade based on their original values.yaml through "helm get values".

The values.yaml is not just an example file. It acts as the default value if no explicit value is specified through `--set` or `--values`.
Helm reference: https://helm.sh/docs/chart_template_guide/values_files/

I just tried it on my cluster and the internal kvdb overrides the existing external etcd endpoints.

2022-07-24 04:44 UTC, haibinxie commented
> > > Won't this break migrated customers who have etcdEndpoints set? We will default to internal kvdb for them and the etcd endpoints would be ignored. I guess we will have to update the logic in the storagecluster spec.
> > 
> > 
> > the migrated customer should have no impact as they need to upgrade based on their original values.yaml through "helm get values".
> 
> The values.yaml is not just an example file. It acts as the default value if no explicit value is specified through `--set` or `--values`. Helm reference: https://helm.sh/docs/chart_template_guide/values_files/
> 
> I just tried it on my cluster and the internal kvdb overrides the existing external etcd endpoints.

Yes, if nothing is given then it would use the default values. since the original values.yaml with etcdEndpoint is not default values.yaml, upgrading from non default values.yaml to default values.yaml is ok to break.

2022-07-25 18:56 UTC, haibinxie commented
After discussion with Piyush, this will break migration, hence closing it, we will keep internalKVDB default to false.

2022-07-25 18:56 UTC, closed without merging