PWX-37683 | Add missing fields in cloudstorage and storage
portworx/helm pull request #604
Opened 2024-07-25 07:53 UTC by hitesh-wani-px

**What this PR does / why we need it**:
Add missing fields in cloudstorage and storage in storagecluster template

**Which issue(s) this PR fixes** (optional)
Closes #https://purestorage.atlassian.net/browse/PWX-37683

**Special notes for your reviewer**:

2024-07-25 08:22 UTC, hitesh-wani-px commented
**Testing Note:**
**1. CloudStorage** 
 Tested with following cloudStorage specific values
```yaml
internalKVDB: true
drives: "type=gp2,size=200;type=gp3,size=500"                          
provider: gce                           
journalDevice: "type=journal"
maxStorageNodesPerZone: 1             
maxStorageNodes: 1              
systemMetadataDevice: "type=gp2,size=100"
kvdbDevice: "type=node-kvdb"
```
StorageCluster generated for above values
```yaml
kind: StorageCluster
apiVersion: core.libopenstorage.org/v1
metadata:
  name: "mycluster"
  namespace: kube-system
  annotations:
  labels:
    heritage: "Helm"
    release: "my-release"
    chart: "portworx-3.1.0"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/instance: "my-release"
spec:
  image: portworx/oci-monitor:3.1.0
  imagePullPolicy: Always

  kvdb:
    internal: true
  cloudStorage:
    provider: gce
    deviceSpecs:
      - type=gp2,size=200
      - type=gp3,size=500
    systemMetadataDeviceSpec: type=gp2,size=100
    journalDeviceSpec: type=journal
    kvdbDeviceSpec: type=node-kvdb
    maxStorageNodesPerZone: 1
    maxStorageNodes: 1
  secretsProvider: k8s

  env:
  - name: PX_SECRETS_NAMESPACE
    value: portworx

  stork:
    enabled: true
  csi:
    enabled: false
``` 
**2. storage**
 Tested with following storage specific values
```yaml
internalKVDB: true
drives: "/dev/sda;/dev/sdb;/dev/sdc"                          
journalDevice: "/dev/sdd"
systemMetadataDevice: "/dev/sde"
kvdbDevice: "type=node-kvdb"
cacheDevices: "/dev/one;/dev/two"
usefileSystemDrive: true        
```
StorageCluster generated for above values
```yaml
kind: StorageCluster
apiVersion: core.libopenstorage.org/v1
metadata:
  name: "mycluster"
  namespace: kube-system
  annotations:
  labels:
    heritage: "Helm"
    release: "my-release"
    chart: "portworx-3.1.0"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/instance: "my-release"
spec:
  image: portworx/oci-monitor:3.1.0
  imagePullPolicy: Always

  kvdb:
    internal: true
  storage:
    devices:
        - /dev/sda
        - /dev/sdb
        - /dev/sdc
    cacheDevices:
        - /dev/one
        - /dev/two
    forceUseDisks: true
    useAll: true
    systemMetadataDevice: /dev/sde
    journalDevice: /dev/sdd
  secretsProvider: k8s

  env:
  - name: PX_SECRETS_NAMESPACE
    value: portworx

  stork:
    enabled: true
  csi:
    enabled: false
```
**Unit test cases results:**
```
--- PASS: TestStorageClusterHelmTemplate (0.00s)
    --- PASS: TestStorageClusterHelmTemplate/TestCustomRegistry (0.07s)
    --- PASS: TestStorageClusterHelmTemplate/TestStorageSpec (0.08s)
    --- PASS: TestStorageClusterHelmTemplate/TestCloudStorage (0.08s)
    --- PASS: TestStorageClusterHelmTemplate/TestAllComponentsEnabled (0.08s)
    --- PASS: TestStorageClusterHelmTemplate/TestCloudStorageAKS (0.08s)
    --- PASS: TestStorageClusterHelmTemplate/TestDefaultChartValues (0.08s)
    --- PASS: TestStorageClusterHelmTemplate/TestExternalETCD (0.08s)
    --- PASS: TestStorageClusterHelmTemplate/TestPlacementTolerations (0.09s)
PASS
ok      github.com/portworx/helm/test/portworx  0.117s
```

2024-07-29 05:57 UTC, vinayakshnd requested changes

2024-07-29 07:06 UTC, hitesh-wani-px commented on test/portworx/testspec/storagecluster_storage.yaml
> +    journalDevice: /dev/sdd
Done @vinayakshnd 
Resolved issue. Now `kvdbDevice` is getting populated in template.

2024-07-29 07:54 UTC, vinayakshnd approved these changes
LGTM

2024-07-29 07:55 UTC, merged